#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import re
import json

import telebot
from telebot.types import Message, ReplyKeyboardMarkup, KeyboardButton
from langdetect import detect, DetectorFactory
from gigachat import GigaChat
import requests

DetectorFactory.seed = 0

# ========== НАСТРОЙКИ (из переменных окружения Railway) ==========
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")
GIGACHAT_CREDENTIALS = os.environ.get("GIGACHAT_CREDENTIALS")
SAPLING_API_KEY = os.environ.get("SAPLING_API_KEY")
DEMO_PASSWORD = "peter2026"
SAPLING_URL = "https://api.sapling.ai/api/v1/aidetect"

# ========== ИНИЦИАЛИЗАЦИЯ ==========
bot = telebot.TeleBot(TELEGRAM_TOKEN)
giga = GigaChat(credentials=GIGACHAT_CREDENTIALS, verify_ssl_certs=False)

authorized_users = set()
user_language = {}

# ========== ТЕКСТЫ ==========
TEXTS = {
    "ru": {
        "welcome": "🤖 *AI Detect — анализ текста на генерацию нейросетями*\n\nНажми кнопку *▶️ START*, чтобы начать работу.",
        "enter_password": "🔐 *Введите пароль для доступа к боту*",
        "wrong_password": "❌ *Неверный пароль!*\n\nДоступ запрещён.",
        "access_granted": "✅ *Доступ разрешён!*\n\nБот готов к работе.",
        "ask_for_text": "📝 *Отправьте текст для проверки:*",
        "empty_text": "❌ Текст не может быть пустым.",
        "unknown_lang": "❌ Не удалось определить язык. Отправьте текст на русском или английском.",
        "analyzing": "🔍 Анализирую {} текст...",
        "error": "❌ Ошибка: {}",
        "result_title": "РЕЗУЛЬТАТ ПРОВЕРКИ",
        "ai": "СГЕНЕРИРОВАН ИИ",
        "human": "НАПИСАН ЧЕЛОВЕКОМ",
        "lang_label": "Язык",
        "confidence_label": "Уверенность",
        "russian": "🇷🇺 Русский",
        "english": "🇬🇧 English",
        "lang_changed": "🌐 Язык интерфейса изменён на *Русский*"
    },
    "en": {
        "welcome": "🤖 *AI Detect — text generation analysis*\n\nPress *▶️ START* to begin.",
        "enter_password": "🔐 *Enter password to access the bot*",
        "wrong_password": "❌ *Wrong password!*\n\nAccess denied.",
        "access_granted": "✅ *Access granted!*\n\nBot is ready.",
        "ask_for_text": "📝 *Send text for analysis:*",
        "empty_text": "❌ Text cannot be empty.",
        "unknown_lang": "❌ Cannot detect language. Send text in Russian or English.",
        "analyzing": "🔍 Analyzing {} text...",
        "error": "❌ Error: {}",
        "result_title": "RESULT",
        "ai": "GENERATED BY AI",
        "human": "WRITTEN BY HUMAN",
        "lang_label": "Language",
        "confidence_label": "Confidence",
        "russian": "🇷🇺 Russian",
        "english": "🇬🇧 English",
        "lang_changed": "🌐 Interface language changed to *English*"
    }
}

def get_text(user_id, key):
    lang = user_language.get(user_id, "ru")
    return TEXTS.get(lang, TEXTS["ru"]).get(key, TEXTS["ru"][key])

def get_start_keyboard():
    kb = ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
    kb.add(KeyboardButton("▶️ START"))
    kb.add(KeyboardButton("🌐 Language"))
    return kb

def get_main_keyboard():
    kb = ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
    kb.add(KeyboardButton("🔎 Проверить текст"))
    kb.add(KeyboardButton("🌐 Language"))
    return kb

def remove_kb():
    return telebot.types.ReplyKeyboardRemove()

# ========== ОСНОВНЫЕ ФУНКЦИИ ==========
def check_russian(text):
    try:
        prompt = f"Ты детектор ИИ. Ответь JSON: {{'is_ai': true/false, 'confidence': 0-100, 'explanation': 'объяснение'}}. Текст: {text[:1000]}"
        resp = giga.chat(prompt)
        reply = resp.choices[0].message.content
        match = re.search(r'\{.*\}', reply, re.DOTALL)
        if match:
            res = json.loads(match.group())
            return {"is_ai": res.get("is_ai", False), "confidence": res.get("confidence", 50), "explanation": res.get("explanation", "")}, None
        return {"is_ai": False, "confidence": 50, "explanation": "Не удалось распознать"}, None
    except Exception as e:
        return None, str(e)

def check_english(text):
    if len(text.strip()) < 20:
        return {"is_ai": False, "confidence": 0, "explanation": None}, None
    try:
        r = requests.post(SAPLING_URL, json={"key": SAPLING_API_KEY, "text": text}, timeout=30)
        if r.status_code == 200:
            score = r.json().get("score", 0.5)
            return {"is_ai": score > 0.6, "confidence": int(score * 100), "explanation": None}, None
        return None, f"API error: {r.status_code}"
    except Exception as e:
        return None, str(e)

def detect_lang(text):
    try:
        lang = detect(text)
        if lang == 'ru': return "russian"
        if lang == 'en': return "english"
        return "unknown"
    except:
        return "unknown"

def format_result(user_id, lang, detection, error):
    if error:
        return get_text(user_id, "error").format(error)
    if not detection:
        return "❌ Ошибка"
    
    is_ai = detection["is_ai"]
    conf = detection["confidence"]
    icon = "🤖" if is_ai else "👤"
    color = "🔴" if is_ai else "🟢"
    status = get_text(user_id, "ai") if is_ai else get_text(user_id, "human")
    lang_display = get_text(user_id, "russian") if lang == "russian" else get_text(user_id, "english")
    
    res = f"{icon} *{get_text(user_id, 'result_title')}*\n\n{color} *{status}*\n\n🌐 *{get_text(user_id, 'lang_label')}:* {lang_display}\n📊 *{get_text(user_id, 'confidence_label')}:* {conf}%"
    
    if lang == "russian" and detection.get("explanation"):
        res += f"\n\n💬 *Объяснение:* {detection['explanation']}"
    return res

# ========== ОБРАБОТЧИКИ ==========
@bot.message_handler(commands=['start'])
def cmd_start(m):
    uid = m.from_user.id
    if uid not in user_language:
        user_language[uid] = "ru"
    bot.send_message(m.chat.id, get_text(uid, "welcome"), parse_mode="Markdown", reply_markup=get_start_keyboard())

@bot.message_handler(func=lambda m: m.text == "🌐 Language")
def show_language_choice(m):
    uid = m.from_user.id
    kb = ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
    kb.add(KeyboardButton("🇷🇺 Русский"), KeyboardButton("🇬🇧 English"))
    kb.add(KeyboardButton("▶️ START"))
    bot.send_message(m.chat.id, "🌐 *Выберите язык / Choose language:*", parse_mode="Markdown", reply_markup=kb)

@bot.message_handler(func=lambda m: m.text in ["🇷🇺 Русский", "🇬🇧 English"])
def set_language(m):
    uid = m.from_user.id
    if m.text == "🇷🇺 Русский":
        user_language[uid] = "ru"
    else:
        user_language[uid] = "en"
    bot.send_message(m.chat.id, get_text(uid, "lang_changed"), parse_mode="Markdown", reply_markup=get_start_keyboard())

@bot.message_handler(func=lambda m: m.text == "▶️ START")
def handle_start(m):
    uid = m.from_user.id
    bot.send_message(m.chat.id, get_text(uid, "enter_password"), parse_mode="Markdown", reply_markup=remove_kb())
    bot.register_next_step_handler(m, check_pass)

def check_pass(m):
    uid = m.from_user.id
    if m.text.strip() == DEMO_PASSWORD:
        authorized_users.add(uid)
        bot.send_message(m.chat.id, get_text(uid, "access_granted"), parse_mode="Markdown", reply_markup=get_main_keyboard())
    else:
        bot.send_message(m.chat.id, get_text(uid, "wrong_password"), parse_mode="Markdown", reply_markup=get_start_keyboard())

@bot.message_handler(func=lambda m: m.text == "🔎 Проверить текст")
def ask_text(m):
    uid = m.from_user.id
    if uid not in authorized_users:
        bot.send_message(m.chat.id, get_text(uid, "wrong_password"), reply_markup=get_start_keyboard())
        return
    bot.send_message(m.chat.id, get_text(uid, "ask_for_text"), parse_mode="Markdown", reply_markup=remove_kb())
    bot.register_next_step_handler(m, analyze)

def analyze(m):
    uid = m.from_user.id
    text = m.text.strip()
    if not text:
        bot.send_message(m.chat.id, get_text(uid, "empty_text"), reply_markup=get_main_keyboard())
        return
    
    bot.send_chat_action(m.chat.id, "typing")
    lang = detect_lang(text)
    
    if lang == "unknown":
        bot.send_message(m.chat.id, get_text(uid, "unknown_lang"), reply_markup=get_main_keyboard())
        return
    
    lang_name = "русский" if lang == "russian" else "English"
    bot.send_message(m.chat.id, get_text(uid, "analyzing").format(lang_name))
    
    if lang == "russian":
        res, err = check_russian(text)
    else:
        res, err = check_english(text)
    
    answer = format_result(uid, lang, res, err)
    bot.send_message(m.chat.id, answer, parse_mode="Markdown", reply_markup=get_main_keyboard())

@bot.message_handler(func=lambda message: True)
def handle_any_message(message):
    user_id = message.from_user.id
    if user_id not in authorized_users:
        bot.send_message(
            message.chat.id,
            "👋 *Добро пожаловать!*\n\nЧтобы начать работу, нажмите кнопку ниже или введите команду /start",
            parse_mode="Markdown",
            reply_markup=get_start_keyboard()
        )

# ========== ЗАПУСК ==========
if __name__ == "__main__":
    print("✅ Бот запущен!")
    print("🔐 Пароль: peter2026")
    bot.infinity_polling()